---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ../../data_bags

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65

suites:
  - name: default
    run_list:
      - recipe[users::default]
    attributes:
